POST http://localhost:3333/api/short
Content-Type: application/json

{
  "code": "jhalan_bipal",
  "original_url": "https://www.google.com"
}

###

GET http://localhost:3333/api/short

###

GET http://localhost:3333/api/short/isaac_S.Silva

###

DELETE http://localhost:3333/api/short/10

###

GET http://localhost:3333/isaac_S.Silva

###

GET http://localhost:3333/api/metrics

###